<a href="https://colab.research.google.com/github/disha2101/Great_Learning/blob/main/Great_Learning_ML_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Numpy is Numerical Python and is the core lib for numeric and scientific computing*

In [15]:
import numpy as np

In [ ]:
a = np.array([1,2,3]) #1d array
a


array([1, 2, 3])

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) #2d array
a


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(a)

numpy.ndarray

*Initialising numpy array with zeros*

In [ ]:
 b =np.zeros((1,2))
 b

array([[0., 0.]])

*Initialising numpy array with same number*

In [ ]:
c = np.full((2,6),10)
c

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

*Initialising numpy array within a range*

In [ ]:
d= np.arange(10,20,2)
d

array([10, 12, 14, 16, 18])

In [ ]:
e= np.arange(10,20)
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

*Initialising numpy array with random numbers*

In [ ]:
f =np.random.randint(10,200,10)
f

array([ 28, 154, 171,  57,  95, 123,  50,  36, 141, 142])

*Checking the shape of numpy arrays*

In [ ]:
b.shape

(1, 2)

In [16]:
n1 = np.array([1,2,3,4])
n2 = np.array([4,5,8,9])


In [4]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 7, 5, 8, 9])

In [5]:
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [7, 5, 8, 9]])

In [6]:
np.column_stack((n1,n2))

array([[1, 7],
       [2, 5],
       [3, 8],
       [4, 9]])

In [8]:
np.setdiff1d(n1,n2)

array([1, 2, 3, 4])

In [13]:
np.intersect1d(n1,n2)

array([4])

In [14]:
np.setdiff1d(n2,n1)

array([5, 8, 9])

In [18]:
np.sum([n1,n2])

36

In [19]:
np.sum([n1,n2],axis=0) #adding values column vise

array([ 5,  7, 11, 13])

In [20]:
np.sum([n1,n2],axis=1) #adding values row wise

array([10, 26])

In [21]:
n1 -1 

array([0, 1, 2, 3])

In [22]:
n1*2

array([2, 4, 6, 8])

In [23]:
n1/3


array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [24]:
np.mean(n2)

6.5

In [25]:
np.std(n2)

2.0615528128088303

In [26]:
np.median(n2)

6.5

In [28]:
np.save('my_numpy',n1) #saving n1 array in my_numpy

In [29]:
n2 = np.load('my_numpy.npy')
n2

array([1, 2, 3, 4])

*Pandas stands for panel data and is the core library for data manipulation and data analysis*

*It consists of single and multidimensional data as series objects and dataframe respectively*

In [30]:
import pandas as pd 

In [31]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [32]:
type(s1)

pandas.core.series.Series

In [34]:
s1 = pd.Series([2,3,4,5,6])
s1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [36]:
s1 = pd.Series([1,2,3,4,5],index=['hello','its','disha','d','e'])
s1

hello    1
its      2
disha    3
d        4
e        5
dtype: int64

In [39]:
a = pd.Series({'a':100,'b':122,'c':234},index=['a','b','c','d'])
a

a    100.0
b    122.0
c    234.0
d      NaN
dtype: float64

In [40]:
n1+n2

array([2, 4, 6, 8])

In [41]:
n1-1

array([0, 1, 2, 3])

In [42]:
n2-1

array([0, 1, 2, 3])

In [43]:
df1 = pd.DataFrame({'Name':['V','A','D','C'],'Roll No':[1,2,3,4]})
df1

Name  Roll No
0    V        1
1    A        2
2    D        3
3    C        4

In [45]:
iris= pd.read_csv('iris.csv')
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [46]:
iris.shape

(150, 5)

In [47]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [48]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [49]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [50]:
iris.iloc[0:8,0:7] # extracting rows from 0 to 8 and extracting columns from 0 to 7

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa

In [54]:
iris.loc[15:60,{'Sepal.Length','Sepal.Width'}]


Sepal.Width  Sepal.Length
15          4.4           5.7
16          3.9           5.4
17          3.5           5.1
18          3.8           5.7
19          3.8           5.1
20          3.4           5.4
21          3.7           5.1
22          3.6           4.6
23          3.3           5.1
24          3.4           4.8
25          3.0           5.0
26          3.4           5.0
27          3.5           5.2
28          3.4           5.2
29          3.2           4.7
30          3.1           4.8
31          3.4           5.4
32          4.1           5.2
33          4.2           5.5
34          3.1           4.9
35          3.2           5.0
36          3.5           5.5
37          3.6           4.9
38          3.0           4.4
39          3.4           5.1
40          3.5           5.0
41          2.3           4.5
42          3.2           4.4
43          3.5           5.0
44          3.8           5.1
45          3.0           4.8
46          3.8           5.1
47          3.2           4.6
48          3.7           5.3
49          3.3           5.0
50          3.2           7.0
51          3.2           6.4
52          3.1           6.9
53          2.3           5.5
54          2.8           6.5
55          2.8           5.7
56          3.3           6.3
57          2.4           4.9
58          2.9           6.6
59          2.7           5.2
60          2.0           5.0

In [55]:
iris.drop('Sepal.Length',axis=1)

Sepal.Width  Petal.Length  Petal.Width    Species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [56]:
iris.drop([1,2,3,4],axis=0) #dropped [1,2,3,4] rows

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[146 rows x 5 columns]

In [57]:
iris.min()

Sepal.Length       4.3
Sepal.Width          2
Petal.Length         1
Petal.Width        0.1
Species         setosa
dtype: object

In [58]:
iris.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

In [59]:
iris.median()

Sepal.Length    5.80
Sepal.Width     3.00
Petal.Length    4.35
Petal.Width     1.30
dtype: float64

In [60]:
iris.std()

Sepal.Length    0.828066
Sepal.Width     0.435866
Petal.Length    1.765298
Petal.Width     0.762238
dtype: float64

In [61]:
def double_make(s):
  return s*2

iris[['Sepal.Length','Sepal.Width']].apply(double_make)

Sepal.Length  Sepal.Width
0            10.2          7.0
1             9.8          6.0
2             9.4          6.4
3             9.2          6.2
4            10.0          7.2
..            ...          ...
145          13.4          6.0
146          12.6          5.0
147          13.0          6.0
148          12.4          6.8
149          11.8          6.0

[150 rows x 2 columns]

In [62]:
iris.sort_values(by='Sepal.Length')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [63]:
iris['Species'].value_counts

<bound method IndexOpsMixin.value_counts of 0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object>